### ISSUE TITLE
Please do not have plugin run if it project type is "pom"

### ISSUE THREAD

**Issue by rvowles** [Jasig/sass-maven-plugin#38]
If you do a 

`if (project.getType().equals("pom")) return;`

on the execute, this means we can force the plugin to run on child projects. Otherwise we can only put it in pluginManagement and then its a "suggestion".

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
