### ISSUE TITLE
Error during build caused by <gemPaths> configuration

### ISSUE THREAD

**Issue by justindsmith** [Jasig/sass-maven-plugin#41]
I'm getting a <gemPaths> configuration error during build. I've tried both explicitly setting the <gemPaths> and leaving it as the default and the error is always the same.

> [ERROR] BUILD ERROR
> [INFO] ------------------------------------------------------------------------
> [INFO] Failed to configure plugin parameters for: org.jasig.maven:sass-maven-plugin:1.1.1
> Cause: Cannot assign configuration entry 'gemPaths' to 'class [Ljava.lang.String;' from 'null', which is of type class java.lang.String

I've tried emptying my repository and building again, but no luck.

Stacktraced build output and configured pom.xml in the link below:
https://gist.github.com/justindsmith/7cac80c66c654fc46dfc

Versions:
- sass-maven-plugin: 1.1.1
- maven: 2.2.1
- java: 1.7.0_17

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
