### ISSUE TITLE
Compass build does not pick up config.rb

### ISSUE THREAD

**Issue by zackarychapple** [Jasig/sass-maven-plugin#43]
``` xml
<plugin>
    <groupId>org.jasig.maven</groupId>
    <artifactId>sass-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>sassProcessResources</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>update-stylesheets</goal>
            </goals>
            <configuration>
                <useCompass>true</useCompass>
                <sassSourceDirectory>${basedir}/src/main/scss</sassSourceDirectory>
                <destination>${project.build.outputDirectory}/styleguide-components/resources/css</destination>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I have a config.rb in the root of my "styleguide" folder which is in the "scss" folder.  

If I run compass compile from the command line the config.rb gets picked up and the sprite I am trying to generate gets created as expected, however if I try to update-stylesheets using the maven plugin it fails with the below error.    

``` java
No files were found in the load path matching "common_icons/*.png". Your current load paths are: ./images
```

How do I actually get the plugin to pick up the config.rb file?

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
