### ISSUE TITLE
M2E connector

### ISSUE THREAD

**Issue by robianmcd** [Jasig/sass-maven-plugin#48]
I couldn't get the m2e connector found here https://code.google.com/a/eclipselabs.org/p/m2e-jasig-sass-connector/ to do anything. Is there anything I need to do after installing it into eclipse. The plugin is not being run on Eclipse's auto build or on a manual build.

Here is what the plugin looks like in my pom

``` xml
<plugin>
    <groupId>org.jasig.maven</groupId>
    <artifactId>sass-maven-plugin</artifactId>
    <version>1.1.0</version>
    <executions>
    </executions>
    <configuration>
        <resources>

            <resource>
                <source>
                    <directory>${basedir}/WebContent/stylesheets/sass</directory>
                </source>
                <destination>${basedir}/WebContent/stylesheets/css</destination>
            </resource>

        </resources>
        <useCompass>true</useCompass>
    </configuration>
</plugin>
```

I tried reducing the version number to 1.0.0 but it didn't make a difference.

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
