### ISSUE TITLE
Slow SASS compilation 

### ISSUE THREAD

**Issue by theyelllowdart** [Jasig/sass-maven-plugin#49]
On my projects I tie SASS compilation into the package lifecycle and compiling SASS takes up a good portion of the build time. Especially, on travis where I do: 
- mvn install -DskipTests
- mvn integration-tests

Assuming the user doesn't run a clean operation each time, we could could try checking if any files have changed before running the expensive sass compilation process?

NHibernate attempts to bypass unnecessary compilation by storing when files were written: http://nhforge.org/blogs/nhibernate/archive/2009/03/13/an-improvement-on-sessionfactory-initialization.aspx

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
