### ISSUE TITLE
sass:watch looping when no changes are happening

### ISSUE THREAD

**Issue by adamyocum** [Jasig/sass-maven-plugin#50]
I have just started using this plugin, so maybe I missed a configuration or something, but this  is what I'm seeing.  The sass:watch command compiling my .scss files about every second, even when no changes are being made to them.  I am running Windows 7 64bit with an SSD harddrive.  I thought maybe this has been reported before, but couldn't find it in your issues.  Any tips would be great.  I'll update if I find anything as to the cause.

Thanks,
Adam

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
