### ISSUE TITLE
Support for Compass configuration properties and callbacks

### ISSUE THREAD

**Issue by breun** [Jasig/sass-maven-plugin#51]
I'm currently using gem-maven-plugin to use Compass in a Maven build and I was trying to migrate to sass-maven-plugin.

However, we're using a config.rb file for Compass with soms configuration properties and callbacks (as documented on http://compass-style.org/help/tutorials/configuration-reference/ ) and I don't see a way to pass these properties and callbacks to sass-maven-plugin. Is this possible?

Or is it possible to have sass-maven-plugin use our existing config.rb for Compass?

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
