### ISSUE TITLE
Compilation quietly fails when directory path has curly braces

### ISSUE THREAD

**Issue by CodeFarmer** [Jasig/sass-maven-plugin#56]
See this guy's stackoverflow question: https://stackoverflow.com/questions/21314827/maven-build-with-sass-does-not-work-in-jenkins

I made a directory on my local machine called '{a}' and found I could replicate his issue by building from it, and worked around it by only passing relative paths to the SASS plugin. It would be good not to have to know/do this though, and also good for the plugin to complain if it thinks its source directory does not exist.

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
