### ISSUE TITLE
Explain "watch"

### ISSUE THREAD

**Issue by cowwoc** [Jasig/sass-maven-plugin#59]
Please document how http://developer.jasig.org/projects/sass-maven-plugin/1.1.1/watch-mojo.html is supposed to work.

I assume this is supposed to watch SCSS files and every time they get modified update the corresponding CSS file.

Thing is, what starts/stops the watch process?

I run my development server using "mvn exec:exec". Is there a way for me to cause the "watch" process to run so long as that server is up?

**Comment by Srikanth-GitHub** [comment]
Hi.. have gone through above discussion. But still am not clear how to configure "sass:watch" on pom.xml. have configured something like below. "update-stylesheets" goal working fine but not watch. Am i missing any configuration here. How "watch" goal will be picked up?

It would be great if some one share example configuration.

<plugin>
<groupId>nl.geodienstencentrum.maven</groupId>
                        <artifactId>sass-maven-plugin</artifactId>
                        <version>2.20</version>
                        
<configuration>

                            <resources>
                                <resource>
                                    <source>
                                        <directory>${basedir}/src/main/content/jcr_root/etc</directory>
                                        <includes>
                                            <include>/**/scss</include>
                                        </includes>
                                    </source>
                                    <relativeOutputDirectory>../css</relativeOutputDirectory>
                                    <destination>${basedir}/src/main/content/jcr_root/etc/</destination>
                                </resource>
                            </resources>
                        </configuration>

                        <executions>
                            <execution>
                                <id>generate-css</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>update-stylesheets</goal>
                                    <goal>watch</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
