### ISSUE TITLE
Configuration documentation?

### ISSUE THREAD

**Issue by jameshfisher** [Jasig/sass-maven-plugin#61]
Is there any? I stumbled across the configuration option `useCompass`, but can't see anything about it in [the README](https://github.com/Jasig/sass-maven-plugin/blob/master/README.md) or [this documentation page](http://developer.jasig.org/projects/sass-maven-plugin/1.1.1/plugin-info.html).

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
