### ISSUE TITLE
Error in running the ruby script from maven

### ISSUE THREAD

**Issue by ghost** [Jasig/sass-maven-plugin#66]
I give following command: mvn clean install -X
and I get:
Hi,
I am getting following error:

env['GEM_PATH'] += ENV['GEM_PATH'] unless ENV['GEM_PATH'].nil?
Gem.paths = env
require 'sass/plugin'
require 'java'
Sass::Plugin.options.merge!(
    :always_update => true,
    :cache_location => '/Users/work/git/gpp/content/target/sass_cache',
    :css_location => '/Users/work/git/gpp/content/src/main/content/jcr_root/etc/designs/gpp/guide/css',
    :debug_info => null,
    :style => null,
    :template_location => '/Users/work/git/gpp/content/src/main/content/jcr_root/etc/designs/gpp/guide/sass'
)
Sass::Plugin.on_compilation_error {|error, template, css| $compiler_callback.compilationError(error.message, template, css) }
Sass::Plugin.on_updated_stylesheet {|template, css| $compiler_callback.updatedStylesheeet(template, css) }
Sass::Plugin.on_template_modified {|template| $compiler_callback.templateModified(template) }
Sass::Plugin.on_template_created {|template| $compiler_callback.templateCreated(template) }
Sass::Plugin.on_template_deleted {|template| $compiler_callback.templateDeleted(template) }
require 'pp'
pp Sass::Plugin.options
Sass::Plugin.update_stylesheets
    at org.jasig.maven.plugin.sass.AbstractSassMojo.executeSassScript(AbstractSassMojo.java:197)
    at org.jasig.maven.plugin.sass.UpdateStylesheetsMojo.execute(UpdateStylesheetsMojo.java:43)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: javax.script.ScriptException: org.jruby.exceptions.RaiseException: (NameError) undefined local variable or method `null' for main:Object
    at org.jruby.embed.jsr223.JRubyEngine.wrapException(JRubyEngine.java:115)
    at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:93)
    at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:153)
    at org.jasig.maven.plugin.sass.AbstractSassMojo.executeSassScript(AbstractSassMojo.java:191)
    ... 22 more
Caused by: org.jruby.exceptions.RaiseException: (NameError) undefined local variable or method`null' for main:Object

Can you please help me understand what this is about and how to fix this?

My POM Snippet looks like:

```
        <plugin>
            <groupId>org.jasig.maven</groupId>
            <artifactId>sass-maven-plugin</artifactId>
            <executions>
                <execution>
                    <id>sassProcessSource</id>
                    <phase>process-sources</phase>
                    <goals>
                        <goal>update-stylesheets</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <sassOptions>
                    <always_update>true</always_update>
                    <style>${sass.OutputStyle}</style>
                    <debug_info>${debug}</debug_info>
                </sassOptions>
                <useCompass>false</useCompass>
                <resources>
                    <resource>
                        <source>
                            <directory>${basedir}/src/main/content/jcr_root/etc/designs/gpp/guide/sass</directory>
                            <includes>
                                <include>*.scss</include>
                            </includes>
                            <excludes />
                        </source>
                        <destination>${basedir}/src/main/content/jcr_root/etc/designs/gpp/guide/css</destination>
                    </resource>
                </resources>
            </configuration>
        </plugin>
```

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
