### ISSUE TITLE
round to 3 decimals 

### ISSUE THREAD

**Issue by venkata82** [Jasig/sass-maven-plugin#69]
round($pixels/$context)  is rounding. I'd like to have a round with 2 or 3 decimals. I'm using this plugin on maven..

sass::script::number.precision on Ruby works it seems. Is there a way i can configure in maven?

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
