### ISSUE TITLE
m2e connector - Failed to execute SASS ruby script:

### ISSUE THREAD

**Issue by nmattia** [Jasig/sass-maven-plugin#72]
I am having troubles using the m2e-jasig-sass-connector(1.0.0). The sass-maven-plugin (1.1.1) runs smoothly when launched from command line (or when maven runs it during deployment), but Eclipse always throws an error when validating the app. It says : 

Failed to execute SASS ruby script:
require 'rubygems'
env = { 'GEM_PATH' => [
    '/home/cowcow/Documents/Projects/eclipse/vicu-app/target/rubygems'
] }
env['GEM_PATH'] += ENV['GEM_PATH'] unless ENV['GEM_PATH'].nil?
Gem.paths = env
require 'sass/plugin'
...
Sass::Plugin.on_template_modified {|template| $compiler_callback.templateModified(template) }
Sass::Plugin.on_template_created {|template| $compiler_callback.templateCreated(template) }
Sass::Plugin.on_template_deleted {|template| $compiler_callback.templateDeleted(template) }
Sass::Plugin.update_stylesheets (org.jasig.maven:sass-maven-plugin:1.1.1:update-stylesheets:generate-css:process-sources)

I unfortunately can't see the actual cause for the error. The plugin is bound to the process-sources maven phase.

**Comment by ezefarina-oe** [comment]
Hi there, I'm having exactly the same issue on

**Comment by ezefarina-oe** [comment]
I've just moved to
<groupId>nl.geodienstencentrum.maven</groupId>
<artifactId>sass-maven-plugin</artifactId>
<version>2.4</version>
It has less documentation but the same config parameters and worked at the very first attempt

**Comment by deelo55** [comment]
Hi, I'm having this issue only on Mac OS X....Windows works fine. Any help much appreciated.

**Comment by jameswennmacher** [comment]
This plug-in is no longer supported.  See updated README.md and https://github.com/Jasig/sass-maven-plugin/network for more recent forks that are maintained and have many of the pull requests integrated into them.

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
