### ISSUE TITLE
Can SASS/Compass version be configurable?

### ISSUE THREAD

**Issue by msdprice** [Jasig/sass-maven-plugin#76]
I've been trying to build a fork of this locally and consume it in another Maven project to no avail (it does not put the rubygems folder in the new project's target, so it the execution fails).

I love this plug in and want to use it, but I need access to newer SASS features.

**Comment by mprins** [comment]
you might try the updated fork at http://www.geodienstencentrum.nl/sass-maven-plugin/plugin-info.html

which has up to date sass, compass, scss-lint included

**Comment by msdprice** [comment]
Mark, you are a gent, thank you! I'll let you know how I get on - as a workaround, I was using gem-maven-plugin and calling the SASS Gem directly.

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
