### ISSUE TITLE
Please add an autoprefixer

### ISSUE THREAD

**Issue by Chris2011** [Jasig/sass-maven-plugin#77]
Most of the time, if you use a new CSS feature like flexbox or whatever, you need to prefix all options with maybe -webkit-flex and so on. In grunt you can use grunt-autoprefixer. What we do now is to call this process. It would be very nice, if we can have this option inside the sass-maven-plugin.

Cheers

Chris

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
